import "dotenv/config";

import { db } from "@/lib/db";
import { calls, carriers, loads, negotiationSessions } from "@/db/schema";

const seedLoads = [
  {
    loadId: "LD-1001",
    origin: "Chicago, IL",
    destination: "Dallas, TX",
    pickupDatetime: new Date("2026-06-12T08:00:00Z"),
    deliveryDatetime: new Date("2026-06-13T18:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "2100.00",
    notes: "No touch freight. Appointment required at delivery.",
    weight: 42000,
    commodityType: "General Freight",
    numOfPieces: 26,
    miles: 925,
    dimensions: "53ft trailer",
  },
  {
    loadId: "LD-1002",
    origin: "Atlanta, GA",
    destination: "Miami, FL",
    pickupDatetime: new Date("2026-06-11T10:00:00Z"),
    deliveryDatetime: new Date("2026-06-12T16:00:00Z"),
    equipmentType: "Reefer",
    loadboardRate: "1850.00",
    notes: "Maintain 34F. Pre-cool required.",
    weight: 38000,
    commodityType: "Produce",
    numOfPieces: 1200,
    miles: 662,
    dimensions: "53ft reefer",
  },
  {
    loadId: "LD-1003",
    origin: "Los Angeles, CA",
    destination: "Phoenix, AZ",
    pickupDatetime: new Date("2026-06-13T06:00:00Z"),
    deliveryDatetime: new Date("2026-06-13T20:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "950.00",
    notes: "Same-day delivery. Driver assist unload.",
    weight: 28000,
    commodityType: "Retail Goods",
    numOfPieces: 18,
    miles: 373,
    dimensions: "48ft trailer",
  },
  {
    loadId: "LD-1004",
    origin: "Houston, TX",
    destination: "Denver, CO",
    pickupDatetime: new Date("2026-06-14T07:00:00Z"),
    deliveryDatetime: new Date("2026-06-16T12:00:00Z"),
    equipmentType: "Flatbed",
    loadboardRate: "3200.00",
    notes: "Tarps and chains required. Oversize permit on file.",
    weight: 45000,
    commodityType: "Steel Coils",
    numOfPieces: 4,
    miles: 1030,
    dimensions: "48ft flatbed",
  },
  {
    loadId: "LD-1005",
    origin: "Indianapolis, IN",
    destination: "Columbus, OH",
    pickupDatetime: new Date("2026-06-12T14:00:00Z"),
    deliveryDatetime: new Date("2026-06-13T08:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "650.00",
    notes: "Drop trailer available at destination.",
    weight: 35000,
    commodityType: "Automotive Parts",
    numOfPieces: 32,
    miles: 176,
    dimensions: "53ft trailer",
  },
  {
    loadId: "LD-1006",
    origin: "Seattle, WA",
    destination: "Portland, OR",
    pickupDatetime: new Date("2026-06-11T09:00:00Z"),
    deliveryDatetime: new Date("2026-06-11T15:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "520.00",
    notes: "Team drivers preferred for tight window.",
    weight: 22000,
    commodityType: "Electronics",
    numOfPieces: 14,
    miles: 174,
    dimensions: "53ft trailer",
  },
  {
    loadId: "LD-1007",
    origin: "Memphis, TN",
    destination: "Nashville, TN",
    pickupDatetime: new Date("2026-06-13T11:00:00Z"),
    deliveryDatetime: new Date("2026-06-13T17:00:00Z"),
    equipmentType: "Reefer",
    loadboardRate: "480.00",
    notes: "Pharmaceutical — seal intact required.",
    weight: 18000,
    commodityType: "Pharmaceuticals",
    numOfPieces: 800,
    miles: 210,
    dimensions: "53ft reefer",
  },
  {
    loadId: "LD-1008",
    origin: "Kansas City, MO",
    destination: "Omaha, NE",
    pickupDatetime: new Date("2026-06-12T12:00:00Z"),
    deliveryDatetime: new Date("2026-06-13T06:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "580.00",
    notes: "Live load at pickup.",
    weight: 40000,
    commodityType: "Paper Products",
    numOfPieces: 22,
    miles: 189,
    dimensions: "53ft trailer",
  },
  {
    loadId: "LD-1009",
    origin: "Charlotte, NC",
    destination: "Richmond, VA",
    pickupDatetime: new Date("2026-06-14T08:00:00Z"),
    deliveryDatetime: new Date("2026-06-14T16:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "720.00",
    notes: "FCFS at both ends.",
    weight: 33000,
    commodityType: "Building Materials",
    numOfPieces: 40,
    miles: 298,
    dimensions: "53ft trailer",
  },
  {
    loadId: "LD-1010",
    origin: "Detroit, MI",
    destination: "Cleveland, OH",
    pickupDatetime: new Date("2026-06-11T13:00:00Z"),
    deliveryDatetime: new Date("2026-06-12T07:00:00Z"),
    equipmentType: "Flatbed",
    loadboardRate: "890.00",
    notes: "Straps only, no tarps needed.",
    weight: 42000,
    commodityType: "Machinery",
    numOfPieces: 2,
    miles: 169,
    dimensions: "48ft flatbed",
  },
  {
    loadId: "LD-1011",
    origin: "San Antonio, TX",
    destination: "El Paso, TX",
    pickupDatetime: new Date("2026-06-13T05:00:00Z"),
    deliveryDatetime: new Date("2026-06-14T14:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "1400.00",
    notes: "Border paperwork handled by shipper.",
    weight: 36000,
    commodityType: "Consumer Goods",
    numOfPieces: 28,
    miles: 550,
    dimensions: "53ft trailer",
  },
  {
    loadId: "LD-1012",
    origin: "Boston, MA",
    destination: "Philadelphia, PA",
    pickupDatetime: new Date("2026-06-12T06:00:00Z"),
    deliveryDatetime: new Date("2026-06-12T20:00:00Z"),
    equipmentType: "Reefer",
    loadboardRate: "1100.00",
    notes: "Continuous temp monitoring required.",
    weight: 30000,
    commodityType: "Seafood",
    numOfPieces: 600,
    miles: 310,
    dimensions: "53ft reefer",
  },
  {
    loadId: "LD-1013",
    origin: "Minneapolis, MN",
    destination: "Milwaukee, WI",
    pickupDatetime: new Date("2026-06-14T10:00:00Z"),
    deliveryDatetime: new Date("2026-06-15T08:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "680.00",
    notes: "Palletized load, standard dock height.",
    weight: 39000,
    commodityType: "Food & Beverage",
    numOfPieces: 36,
    miles: 337,
    dimensions: "53ft trailer",
  },
  {
    loadId: "LD-1014",
    origin: "Salt Lake City, UT",
    destination: "Las Vegas, NV",
    pickupDatetime: new Date("2026-06-11T15:00:00Z"),
    deliveryDatetime: new Date("2026-06-12T10:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "780.00",
    notes: "Early morning delivery slot.",
    weight: 25000,
    commodityType: "Retail Goods",
    numOfPieces: 20,
    miles: 420,
    dimensions: "53ft trailer",
  },
  {
    loadId: "LD-1015",
    origin: "Jacksonville, FL",
    destination: "Savannah, GA",
    pickupDatetime: new Date("2026-06-13T09:00:00Z"),
    deliveryDatetime: new Date("2026-06-13T18:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "540.00",
    notes: "Port drayage adjacent — yard pass required.",
    weight: 32000,
    commodityType: "Import Freight",
    numOfPieces: 24,
    miles: 140,
    dimensions: "53ft trailer",
  },
  {
    loadId: "LD-1016",
    origin: "Chicago, IL",
    destination: "Indianapolis, IN",
    pickupDatetime: new Date("2026-06-12T16:00:00Z"),
    deliveryDatetime: new Date("2026-06-13T04:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "620.00",
    notes: "Night pickup, morning delivery.",
    weight: 41000,
    commodityType: "General Freight",
    numOfPieces: 30,
    miles: 183,
    dimensions: "53ft trailer",
  },
  {
    loadId: "LD-1017",
    origin: "Dallas, TX",
    destination: "Oklahoma City, OK",
    pickupDatetime: new Date("2026-06-14T07:00:00Z"),
    deliveryDatetime: new Date("2026-06-14T15:00:00Z"),
    equipmentType: "Flatbed",
    loadboardRate: "750.00",
    notes: "Pipe load — edge protectors required.",
    weight: 44000,
    commodityType: "Pipe",
    numOfPieces: 12,
    miles: 206,
    dimensions: "48ft flatbed",
  },
  {
    loadId: "LD-1018",
    origin: "Phoenix, AZ",
    destination: "Los Angeles, CA",
    pickupDatetime: new Date("2026-06-13T04:00:00Z"),
    deliveryDatetime: new Date("2026-06-13T22:00:00Z"),
    equipmentType: "Reefer",
    loadboardRate: "1050.00",
    notes: "Frozen at -10F.",
    weight: 35000,
    commodityType: "Frozen Food",
    numOfPieces: 900,
    miles: 373,
    dimensions: "53ft reefer",
  },
  {
    loadId: "LD-1019",
    origin: "Denver, CO",
    destination: "Salt Lake City, UT",
    pickupDatetime: new Date("2026-06-15T08:00:00Z"),
    deliveryDatetime: new Date("2026-06-16T10:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "980.00",
    notes: "Mountain route — experienced drivers only.",
    weight: 37000,
    commodityType: "General Freight",
    numOfPieces: 25,
    miles: 525,
    dimensions: "53ft trailer",
  },
  {
    loadId: "LD-1020",
    origin: "Columbus, OH",
    destination: "Chicago, IL",
    pickupDatetime: new Date("2026-06-12T10:00:00Z"),
    deliveryDatetime: new Date("2026-06-13T06:00:00Z"),
    equipmentType: "Dry Van",
    loadboardRate: "890.00",
    notes: "High-value load — GPS tracking required.",
    weight: 26000,
    commodityType: "Electronics",
    numOfPieces: 16,
    miles: 355,
    dimensions: "53ft trailer",
  },
];

const seedCarriers = [
  {
    mcNumber: "123456",
    legalName: "Midwest Express Logistics LLC",
    dbaName: "Midwest Express",
    status: "Active" as const,
    eligible: true,
  },
  {
    mcNumber: "789012",
    legalName: "Sunbelt Transport Inc",
    dbaName: "Sunbelt Transport",
    status: "Active" as const,
    eligible: true,
  },
  {
    mcNumber: "345678",
    legalName: "Pacific Coast Carriers LLC",
    dbaName: null,
    status: "Active" as const,
    eligible: true,
  },
  {
    mcNumber: "901234",
    legalName: "Great Plains Freight Co",
    dbaName: "GPF Co",
    status: "Active" as const,
    eligible: true,
  },
  {
    mcNumber: "567890",
    legalName: "Suspended Haulers Inc",
    dbaName: null,
    status: "Inactive" as const,
    eligible: false,
  },
  {
    mcNumber: "111111",
    legalName: "Out of Service Trucking LLC",
    dbaName: null,
    status: "Active" as const,
    eligible: false,
  },
];

async function seed() {
  console.log("Seeding database...");

  await db.delete(calls);
  await db.delete(negotiationSessions);
  await db.delete(loads);
  await db.delete(carriers);

  await db.insert(carriers).values(seedCarriers);
  await db.insert(loads).values(seedLoads);

  console.log(
    `Inserted ${seedCarriers.length} carriers and ${seedLoads.length} loads.`,
  );
  process.exit(0);
}

seed().catch((error) => {
  console.error("Seed failed:", error);
  process.exit(1);
});
